replicaCount: 1

image:
  repository: yuvipanda/kubessh-kubessh
  tag: bbba594
  pullPolicy: Always

  name: yuvipanda/kubessh-kubessh
service:
  type: LoadBalancer
  port: 22
  nodePort: 32222

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  enabled: true
